### ISSUE TITLE
Linux support/port possible?

### ISSUE THREAD

**Issue by dhoney** [robertlarue/DF1Comm#1]
Hello,

Do you think it would be possible to get this working under linux?

Are you aware of any VB compilers for Linux that can execute VB?

Thanks!

**Comment by jklemmack** [comment]
This appears to be VB.Net, so you can look at using Mono to compile.  Also be interesting to see if .Net Core could be used, which has first class support for Linux.

**Comment by robertlarue** [comment]
Sorry for the late reply, but yes, this library does work with Mono on Linux. I have used it on Raspbian for my [PLCupdater](https://github.com/robertlarue/PLCupdater) project.
